---

- name: Backup sysctl file | {{ inventory_hostname }} | {{ project_name }}
  copy:
    src: /etc/sysctl.conf
    dest: /etc/sysctl.conf_ansible_bkp
    
- name: Update Sysctl for Performance | {{ inventory_hostname }} | {{ project_name }}
  lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
    state: present
    #backup: yes
  register: sysctl.out
  with_items:
    - "# Settings for Oracle added by ansible"
    - "fs.aio-max-nr = 1048576"
    - "fs.file-max = 6815744"
    - "kernel.shmall = 2097152"
    - "kernel.shmmax = 4294967295"
    - "kernel.shmmni = 4096"
    - "kernel.sem = 250 32000 100 128 "
    - "net.ipv4.ip_local_port_range = 9000 65500"
    - "net.core.rmem_default = 262144"
    - "net.core.rmem_max = 4194304"
    - "net.core.wmem_default = 262144"
    - "net.core.wmem_max = 1048576"
  
- name: Reload sysctl | {{ inventory_hostname }} | {{ project_name }}
  command: /sbin/sysctl -p

- name: Reload sysctl | {{ inventory_hostname }} | {{ project_name }}
  command: /sbin/sysctl -a

- name: Backup security limit configuration | {{ inventory_hostname }} | {{ project_name }}
  copy: 
    src: /etc/security/limits.conf
    dest: /etc/security/limits.conf_ansible_bkp

- name: Update security limit configuration | {{ inventory_hostname }} | {{ project_name }}
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^# End of file'
    state: absent

- name: Update security limit configuration | {{ inventory_hostname }} | {{ porject_name }}
  lineinfile:
    path: /etc/security/limits.conf
    line: "{{ item }}"
    state: present
    backup: yes
  register: sec_limit.out
  with_items:
    - "# Setting up limit by ansible"
    - "oracle  soft    nofile   1024"
    - "oracle  hard    nofile   65536"
    - "oracle  soft    nproc    2047"
    - "oracle  hard    nproc    16384"
    - "oracle  soft    stack    10240"
    - "oracle  hard    stack    32768"
    - "# End of file"

 
